// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wired

import (
	"github.com/google/wire"
	"github.com/m3hm3t/realtime-vwap/internal/core/vwap"
	"github.com/m3hm3t/realtime-vwap/internal/ws_client"
	"github.com/m3hm3t/realtime-vwap/internal/ws_client/handler"
	"github.com/m3hm3t/realtime-vwap/internal/ws_client/subscriber"
)

// Injectors from wired.go:

func InitializeWsClient() ws_client.Client {
	subscriberSubscriber := subscriber.ProvidePairSubscriber()
	calculator := vwap.ProvideVwapCalculator()
	handlerHandler := handler.ProvideVwapHandler(calculator)
	client := ws_client.ProvideWsClient(subscriberSubscriber, handlerHandler)
	return client
}

// wired.go:

var vwapCalculatorSet = wire.NewSet(subscriber.ProvidePairSubscriber, handler.ProvideVwapHandler, vwap.ProvideVwapCalculator)
